version: "2"
services:
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "3001:3000"
  backend:
    build: ./backend/app
    image: backend
    container_name: backend
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d/:ro
      - mysql:/var/lib/mysql

volumes:
  mysql: